name: Build and Release with PNPM

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  actions: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 6.x # Omit or adjust based on your packageManager field

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Compress build artifacts
        run: zip -r build-artifacts.zip ./dist

      - name: Get the release information
        run: echo "UPLOAD_URL=$(gh release view ${{ github.ref_name }} --json uploadUrl -q .uploadUrl)" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./build-artifacts.zip
          asset_name: build-artifacts.zip
          asset_content_type: application/zip
